import { NormalizedCreditReport } from '../../types.js';

/**
 * Golden test fixture: CIBIL Standard Clean Profile
 */
export const goldenCibilCleanReport: NormalizedCreditReport = {
  personal: {
    name: 'Ananya Sharma',
    panMasked: 'ABCDE1234F',
    dateOfBirth: '14/05/1992',
    gender: 'Female',
    mobileMasked: '98765****0',
    emailMasked: 'ananya****@gmail.com',
    address: 'Bandra West, Mumbai, Maharashtra',
    reportDate: '10/08/2026',
    reportNumber: 'CIBIL-2026-0810-77491',
  },
  score: {
    score: 792,
    scoreName: 'CIBIL TransUnion Score 2.0',
    scoreDate: '10/08/2026',
    category: 'Excellent',
    riskLevel: 'Low',
    minScore: 300,
    maxScore: 900,
  },
  accounts: [
    {
      id: 'cibil-gold-1',
      lender: 'HDFC Bank',
      accountType: 'Credit Card',
      isCreditCard: true,
      isSecured: false,
      accountNumberMasked: 'XXXX-XXXX-4512',
      openDate: '12/03/2020',
      lastReportedDate: '31/07/2026',
      sanctionedAmount: 300000,
      currentBalance: 42000,
      overdueAmount: 0,
      paymentHistory: [
        { month: '07/26', monthName: 'Jul', year: 2026, dpd: 0, status: 'NORMAL' },
        { month: '06/26', monthName: 'Jun', year: 2026, dpd: 0, status: 'NORMAL' },
        { month: '05/26', monthName: 'May', year: 2026, dpd: 0, status: 'NORMAL' },
      ],
      normalizedStatus: 'ACTIVE',
      rawStatus: 'Active / Standard',
      negativeRemarks: [],
      maxDPD: 0,
      severity: 'NONE',
      ownershipType: 'Individual',
    },
    {
      id: 'cibil-gold-2',
      lender: 'State Bank of India',
      accountType: 'Home Loan',
      isCreditCard: false,
      isSecured: true,
      accountNumberMasked: 'XXXX-XXXX-8821',
      openDate: '15/01/2022',
      lastReportedDate: '31/07/2026',
      sanctionedAmount: 4500000,
      currentBalance: 3950000,
      overdueAmount: 0,
      paymentHistory: [
        { month: '07/26', monthName: 'Jul', year: 2026, dpd: 0, status: 'NORMAL' },
        { month: '06/26', monthName: 'Jun', year: 2026, dpd: 0, status: 'NORMAL' },
      ],
      normalizedStatus: 'ACTIVE',
      rawStatus: 'Standard / Regular',
      negativeRemarks: [],
      maxDPD: 0,
      severity: 'NONE',
      ownershipType: 'Joint',
    },
  ],
  enquiries: [
    {
      id: 'enq-1',
      date: '15/04/2026',
      institution: 'ICICI Bank',
      purpose: 'Home Loan Balance Transfer',
      amount: 4000000,
    },
  ],
  summary: {
    totalAccounts: 2,
    activeAccounts: 2,
    closedAccounts: 0,
    negativeAccounts: 0,
    totalSanctioned: 4800000,
    totalOutstanding: 3992000,
    totalOverdue: 0,
    creditCardsCount: 1,
    totalCreditCardLimit: 300000,
    totalCreditCardBalance: 42000,
    creditCardUtilizationPct: 14,
    oldestAccountDate: '12/03/2020',
    newestAccountDate: '15/01/2022',
    averageAccountAgeYears: 5.2,
    enquiriesCount: 1,
    enquiriesLast30Days: 0,
    enquiriesLast90Days: 0,
    enquiriesLast180Days: 1,
    securedLoansCount: 1,
    unsecuredLoansCount: 1,
  },
  rawSourceType: 'JSON',
  fileName: 'cibil_clean_sample.json',
  parsedAt: '2026-08-10T10:00:00Z',
};

/**
 * Golden test fixture: Experian Stressed Profile with Write-off and High Utilization
 */
export const goldenExperianStressedReport: NormalizedCreditReport = {
  personal: {
    name: 'Vikramjit Roy',
    panMasked: 'VWXYZ5678G',
    dateOfBirth: '22/11/1985',
    gender: 'Male',
    mobileMasked: '98200****1',
    emailMasked: 'vikram****@rediffmail.com',
    address: 'Salt Lake, Kolkata, West Bengal',
    reportDate: '12/08/2026',
    reportNumber: 'EXP-IND-2026-9921',
  },
  score: {
    score: 588,
    scoreName: 'Experian Credit Score',
    scoreDate: '12/08/2026',
    category: 'Needs Improvement',
    riskLevel: 'Very High',
    minScore: 300,
    maxScore: 900,
  },
  accounts: [
    {
      id: 'exp-stressed-1',
      lender: 'RBL Bank',
      accountType: 'Credit Card',
      isCreditCard: true,
      isSecured: false,
      accountNumberMasked: 'XXXX-XXXX-9912',
      openDate: '18/07/2019',
      lastReportedDate: '31/07/2026',
      sanctionedAmount: 150000,
      currentBalance: 142000,
      overdueAmount: 28000,
      paymentHistory: [
        { month: '07/26', monthName: 'Jul', year: 2026, dpd: 60, status: 'LATE_60' },
        { month: '06/26', monthName: 'Jun', year: 2026, dpd: 30, status: 'LATE_30' },
      ],
      normalizedStatus: 'DELINQUENT',
      rawStatus: 'Overdue DPD 60',
      negativeRemarks: ['Overdue amount of ₹28,000 reported.'],
      maxDPD: 60,
      severity: 'CRITICAL',
      ownershipType: 'Individual',
    },
    {
      id: 'exp-stressed-2',
      lender: 'Bajaj Finance Ltd',
      accountType: 'Consumer Loan',
      isCreditCard: false,
      isSecured: false,
      accountNumberMasked: 'XXXX-XXXX-1144',
      openDate: '10/02/2021',
      lastReportedDate: '15/05/2024',
      sanctionedAmount: 85000,
      currentBalance: 0,
      overdueAmount: 0,
      paymentHistory: [
        { month: '05/24', monthName: 'May', year: 2024, dpd: 'WRT', status: 'WRITTEN_OFF' },
      ],
      normalizedStatus: 'WRITTEN_OFF',
      rawStatus: 'Written Off',
      negativeRemarks: ['Post-writeoff settlement pending NOC.'],
      maxDPD: 180,
      severity: 'CRITICAL',
      ownershipType: 'Individual',
    },
  ],
  enquiries: [
    {
      id: 'enq-s1',
      date: '02/08/2026',
      institution: 'KreditBee',
      purpose: 'Short Term Loan',
      amount: 25000,
    },
    {
      id: 'enq-s2',
      date: '25/07/2026',
      institution: 'PayU Finance',
      purpose: 'Personal Loan',
      amount: 50000,
    },
  ],
  summary: {
    totalAccounts: 2,
    activeAccounts: 1,
    closedAccounts: 1,
    negativeAccounts: 2,
    totalSanctioned: 235000,
    totalOutstanding: 142000,
    totalOverdue: 28000,
    creditCardsCount: 1,
    totalCreditCardLimit: 150000,
    totalCreditCardBalance: 142000,
    creditCardUtilizationPct: 95,
    oldestAccountDate: '18/07/2019',
    newestAccountDate: '10/02/2021',
    averageAccountAgeYears: 6.1,
    enquiriesCount: 2,
    enquiriesLast30Days: 2,
    enquiriesLast90Days: 2,
    enquiriesLast180Days: 2,
    securedLoansCount: 0,
    unsecuredLoansCount: 2,
  },
  rawSourceType: 'JSON',
  fileName: 'experian_stressed_sample.json',
  parsedAt: '2026-08-12T10:00:00Z',
};
